name: Test-GitHubActions

on: 
  push:
    branches:
      - main

runs-on: ubuntu-latest

jobs:
  Clone:
    steps:
    - name: Echo
      run: echo "hello world!" > hello.txt
    - name: Ls
      run: ls -la


  Build:
    steps:
    - name: Ls
      run: ls -la