apiVersion: v1
kind: Service
metadata:
  name: nicereplicaset-service
spec:
  # type: ClusterIP
  type: NodePort
  # type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nicereplicaset-service
  labels:
    app: httpd
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: web
          image: httpd
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi