---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: "ingress-nginx"
  labels:
    app: "postgres"
data:
  API_KEY: "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"
  SECRET_KEY: "ffl@q714d-eewzyh4-e8wuzdxz+ey5_=673qky=zujv#hdy#1s"

  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: "db"


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres"
  namespace: "ingress-nginx"
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:13.13"
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_DB"
              name: "postgres-config"
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "postgres-config"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "postgres-config"
        - name: "POSTGRES_HOST"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_HOST"
              name: "postgres-config"
        - name: "API_KEY"
          valueFrom:
            configMapKeyRef:
              key: "API_KEY"
              name: "postgres-config"
        - name: "SECRET_KEY"
          valueFrom:
            configMapKeyRef:
              key: "SECRET_KEY"
              name: "postgres-config"
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/db-data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace        : ingress-nginx
  name: postgres-pv-claim
  labels:
    app: "postgres"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace        : ingress-nginx
  name: db
spec:
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: "NodePort"