name: Diplom

on:
  push:
    branches:
      - main


jobs:
  # Build_and_Publish_Docker:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./diplom
  #   timeout-minutes: 3
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Cheking file
  #       run: ls -la
      
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_TEST }}
    
  #     - name: Build and push Docker image
  #       run: | 
  #         docker build -t vedenindenis/diplom_web:latest .
  #         docker push vedenindenis/diplom_web:latest



  # Terraform_GKE:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./diplom/.infra
  #   timeout-minutes: 15
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Terraform Format
  #       id: fmt
  #       run: terraform fmt -check

  #     - name: Terraform init
  #       run: terraform init

  #     - name: Terraform plan
  #       run: terraform plan

  #     - name: Terraform aplly
  #       run: terraform apply -auto-approve

  K8S:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Auth K8S
        run: gcloud container clusters get-credentials my-project-kubernetes-409711-gke --region us-central1 --project my-project-kubernetes-409711

      - name: Get list nodes
        run: kubectl get nodes

      - name: Get list service
        run: kubectl get service

      