name: Diplom

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_and_Publish_Docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./diplom
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Cheking file
        run: ls -la
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TEST }}
    
      - name: Build and push Docker image
        run: |
          docker-compose build
          docker images 
# docker build -t vedenindenis/my-image:latest .
# docker push vedenindenis/my-image:latest



  # Terraform_create_GKE:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./diplom
  #   timeout-minutes: 3
      