name: Test-GitHubActions

on: 
  push:
    branches:
      - main


jobs:
  spring-petclinic:
    # strategy:
    #   matrix:
    #     platform: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
    runs-on: ubuntu-latest
    # ${{ matrix.platform }}
    steps:
    - name: Clone
      env:
        github_token: ${{ secrets.TEST_SECRET}}
        # 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 
      run: |
        echo "------ Clone project statrt ------"
        git clone https://$github_token@github.com/tms-dos17-onl/spring-petclinic.git
        ls -la spring-petclinic/
        echo "------ Clone project end ------"

  Build:
    runs-on: ubuntu-latest
    needs: spring-petclinic
    steps:
    - name: Build
      run: ls -la
  
    

  